SWEP.Base = "salat_base" -- base 
SWEP.PrintName = "UMP"
SWEP.Instructions = "Что может еще делать ПП? СТРЕЛЯТЬ В ЛИЦО!"
SWEP.Category = "Оружие"
SWEP.Spawnable = true
SWEP.AdminOnly = false
------------------------------------------
SWEP.Primary.ClipSize = 25
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize * 2
SWEP.Primary.Automatic = true
SWEP.Primary.Ammo = "357"
SWEP.Primary.Cone = 0
SWEP.Primary.Damage = 85
SWEP.Primary.Spread = 0
SWEP.Primary.Sound = "weapons/ump45/ump45-1.wav"
SWEP.Primary.Force = 20
SWEP.ReloadTime = 2
SWEP.ShootWait = 0.09
SWEP.TwoHands = true
SWEP.Secondary.ClipSize = -1
SWEP.Secondary.DefaultClip = -1
SWEP.Secondary.Automatic = false
SWEP.Secondary.Ammo = "none"
------------------------------------------
SWEP.Weight = 5
SWEP.AutoSwitchTo = false
SWEP.AutoSwitchFrom = false
SWEP.HoldType = "smg"
------------------------------------------
SWEP.Slot = 1
SWEP.SlotPos = 2
SWEP.DrawAmmo = true
SWEP.DrawCrosshair = false
SWEP.ViewModel = "models/weapons/salatbase/w_smg_ump45.mdl"
SWEP.WorldModel = "models/weapons/salatbase/w_smg_ump45.mdl"
SWEP.addPos = Vector(10, -0.9, 5)
SWEP.addAng = Angle(-9.8, -0.1, 0)
SWEP.sightPos = Vector(5.2, 8, 0.83)
SWEP.sightAng = Angle(-5, -2, 0)
SWEP.fakeHandRight = Vector(6, -2, 0)
SWEP.fakeHandLeft = Vector(10, -3, -5)
SWEP.Recoil = 0.5