SWEP.Base = "salat_base" -- base 
SWEP.PrintName = "USP-S"
SWEP.Author = "Heckler & Koch"
SWEP.Instructions = "Что может еще делать пистолет? СТРЕЛЯТЬ В ЛИЦО!"
SWEP.Category = "Оружие"
SWEP.Spawnable = true
SWEP.AdminOnly = false
------------------------------------------
SWEP.Primary.ClipSize = 12
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize * 2
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = "357"
SWEP.Primary.Cone = 0
SWEP.Primary.Damage = 70
SWEP.Primary.Spread = 0
SWEP.Primary.Sound = "weapons/usp/usp1.wav"
SWEP.Primary.Force = 20
SWEP.ReloadTime = 2
SWEP.ReloadSound = "weapons/pistol/pistol_reload1.wav"
SWEP.Secondary.ClipSize = -1
SWEP.Secondary.DefaultClip = -1
SWEP.Secondary.Automatic = false
SWEP.Secondary.Ammo = "none"
------------------------------------------
SWEP.Weight = 5
SWEP.AutoSwitchTo = false
SWEP.AutoSwitchFrom = false
SWEP.HoldType = "revolver"
------------------------------------------
SWEP.Slot = 1
SWEP.SlotPos = 2
SWEP.DrawAmmo = true
SWEP.DrawCrosshair = false
SWEP.ViewModel = "models/weapons/salatbase/w_pist_usp_silencer.mdl"
SWEP.WorldModel = "models/weapons/salatbase/w_pist_usp_silencer.mdl"
SWEP.addPos = Vector(5, 0.1, 4)
SWEP.addAng = Angle(-2.5, 4.9, 0)
SWEP.sightPos = Vector(3.7, 15, 1.49)
SWEP.sightAng = Angle(4, 8, 0)
SWEP.fakeHandRight = Vector(3.5, -1.5, 2)
SWEP.DoFlash = false
SWEP.Recoil = 0.5